version: "3.9"
services:

  node-application:
    build: .
    container_name: node-application
    volumes:
      - ./:/app
    ports:
      - "9000:3000"
    restart: always
    
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data 
      - ./scripts:/var/lib/postgresql/scripts
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
 
volumes:
  pgdata: